apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
  creationTimestamp: "2021-08-15T03:11:40Z"
  generation: 1
  labels:
    app: php-basic-framework-web
  name: php-basic-framework-web
  namespace: default
  resourceVersion: "34673"
  selfLink: /apis/apps/v1/namespaces/default/deployments/php-basic-framework-web
  uid: 07438620-f985-4b73-8b79-ff3b523023b9
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: php-basic-framework-web
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: php-basic-framework-web
    spec:
      containers:
      - image: caprilespe/php-basic-framework-web:v1
        imagePullPolicy: IfNotPresent
        name: php-basic-framework-web
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status:
  availableReplicas: 1
  conditions:
  - lastTransitionTime: "2021-08-15T03:12:01Z"
    lastUpdateTime: "2021-08-15T03:12:01Z"
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  - lastTransitionTime: "2021-08-15T03:11:40Z"
    lastUpdateTime: "2021-08-15T03:12:01Z"
    message: ReplicaSet "php-basic-framework-web-7488dbbb45" has successfully progressed.
    reason: NewReplicaSetAvailable
    status: "True"
    type: Progressing
  observedGeneration: 1
  readyReplicas: 1
  replicas: 1
  updatedReplicas: 1
