apiVersion: v1
kind: Service
metadata:
  creationTimestamp: "2021-08-15T03:14:21Z"
  labels:
    app: php-basic-framework-web
  name: php-basic-framework-web
  namespace: default
  resourceVersion: "34787"
  selfLink: /api/v1/namespaces/default/services/php-basic-framework-web
  uid: 6052054b-9f7e-42e7-bcc4-69354e36589e
spec:
  clusterIP: 10.103.101.150
  externalTrafficPolicy: Cluster
  ports:
  - nodePort: 30028
    port: 8001
    protocol: TCP
    targetPort: 8000
  selector:
    app: php-basic-framework-web
  sessionAffinity: None
  type: LoadBalancer
status:
  loadBalancer: {}
